### PR TITLE
Login-UI

### PR DESCRIPTION
**Pull request by nb03**
- Designed and coded the user interface for the homepage of the login/sign up screens. 

- Added styling by means of graphics and text, including a button which redirects user to create an account/log in. 

- Improved the usability of logging in by using minimalistic design to allow user to focus on the most important component of the page, the button that will allow them to start using the web app.

### CODE REVIEW

**Review by HamzaKazmi — COMMENTED** [review]
The login button component should only have the functions and UI of the button and not the login page. 

In the next sprint try to only commit the file that is changed. Otherwise, the UI looks good and has good functionality

**Comment by jghori** [comment]
Overall code is very clean and readable. In future sprints you could potentially provide more dynamic aspects to the landing page as well as a sign in and login button rather than an explore button. This will be more intuitive to the user and will be easier to navigate.

**Comment by nb03** [comment]
> Overall code is very clean and readable. In future sprints you could potentially provide more dynamic aspects to the landing page as well as a sign in and login button rather than an explore button. This will be more intuitive to the user and will be easier to navigate.

what are some dynamic components you like seeing on a landing login page? I will definitely add those in during the next sprint!

**Comment by jghori** [comment]
> > Overall code is very clean and readable. In future sprints you could potentially provide more dynamic aspects to the landing page as well as a sign in and login button rather than an explore button. This will be more intuitive to the user and will be easier to navigate.
> 
> what are some dynamic components you like seeing on a landing login page? I will definitely add those in during the next sprint!

THings such as animations and popping text to catch the users eye, definitely key components of a landing page!

**Comment by defnecelebi** [comment]
> Overall code is very clean and readable. In future sprints you could potentially provide more dynamic aspects to the landing page as well as a sign in and login button rather than an explore button. This will be more intuitive to the user and will be easier to navigate.
I agree with josh on this comment, the comments you added  for UI of the login screen homepage makes the code clean and easy to understand. I also believe that the visuality of the landing page could be better by having more interactive/dynamic aspects to increase the user experience of the application. Since we have 3 more upcoming sprints, I highly suggest to pay more attention to the overall visuality of the pages you work on.

**Pull request closed without merging**
